parameters:
#    zaz_blog.example.class: Zaz\BlogBundle\Example

services:
    zaz_blog.user_registration_complete:
        class: Zaz\BlogBundle\EventListener\RegisterListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }
#    zaz_blog.example:
#        class: %zaz_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
